# Site settings
title: Open source licenses
email: hello@springworks.se
description: Open source licenses
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
